//go:build !ignore_autogenerated

/*
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/awslabs/operatorpkg/status"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryAuth) DeepCopyInto(out *ContainerRegistryAuth) {
	*out = *in
	in.AuthSecretRef.DeepCopyInto(&out.AuthSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryAuth.
func (in *ContainerRegistryAuth) DeepCopy() *ContainerRegistryAuth {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryBasicAuth) DeepCopyInto(out *ContainerRegistryBasicAuth) {
	*out = *in
	in.UsernameSecretRef.DeepCopyInto(&out.UsernameSecretRef)
	in.PasswordSecretRef.DeepCopyInto(&out.PasswordSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryBasicAuth.
func (in *ContainerRegistryBasicAuth) DeepCopy() *ContainerRegistryBasicAuth {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryBasicAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryCredential) DeepCopyInto(out *ContainerRegistryCredential) {
	*out = *in
	if in.Basic != nil {
		in, out := &in.Basic, &out.Basic
		*out = new(ContainerRegistryBasicAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(ContainerRegistryAuth)
		(*in).DeepCopyInto(*out)
	}
	if in.IdentityToken != nil {
		in, out := &in.IdentityToken, &out.IdentityToken
		*out = new(ContainerRegistryIdentityToken)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryCredential.
func (in *ContainerRegistryCredential) DeepCopy() *ContainerRegistryCredential {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryCredential)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryIdentityToken) DeepCopyInto(out *ContainerRegistryIdentityToken) {
	*out = *in
	in.IdentityTokenSecretRef.DeepCopyInto(&out.IdentityTokenSecretRef)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryIdentityToken.
func (in *ContainerRegistryIdentityToken) DeepCopy() *ContainerRegistryIdentityToken {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryIdentityToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryMirror) DeepCopyInto(out *ContainerRegistryMirror) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make([]ContainerRegistryMirrorEndpoint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryMirror.
func (in *ContainerRegistryMirror) DeepCopy() *ContainerRegistryMirror {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryMirror)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistryMirrorEndpoint) DeepCopyInto(out *ContainerRegistryMirrorEndpoint) {
	*out = *in
	if in.TLSSecretRef != nil {
		in, out := &in.TLSSecretRef, &out.TLSSecretRef
		*out = new(corev1.SecretReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistryMirrorEndpoint.
func (in *ContainerRegistryMirrorEndpoint) DeepCopy() *ContainerRegistryMirrorEndpoint {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistryMirrorEndpoint)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContainerRegistrySpec) DeepCopyInto(out *ContainerRegistrySpec) {
	*out = *in
	if in.Mirrors != nil {
		in, out := &in.Mirrors, &out.Mirrors
		*out = make([]ContainerRegistryMirror, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = make([]ContainerRegistryCredential, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContainerRegistrySpec.
func (in *ContainerRegistrySpec) DeepCopy() *ContainerRegistrySpec {
	if in == nil {
		return nil
	}
	out := new(ContainerRegistrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleNodeClass) DeepCopyInto(out *ExoscaleNodeClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleNodeClass.
func (in *ExoscaleNodeClass) DeepCopy() *ExoscaleNodeClass {
	if in == nil {
		return nil
	}
	out := new(ExoscaleNodeClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleNodeClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleNodeClassList) DeepCopyInto(out *ExoscaleNodeClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ExoscaleNodeClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleNodeClassList.
func (in *ExoscaleNodeClassList) DeepCopy() *ExoscaleNodeClassList {
	if in == nil {
		return nil
	}
	out := new(ExoscaleNodeClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ExoscaleNodeClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleNodeClassSpec) DeepCopyInto(out *ExoscaleNodeClassSpec) {
	*out = *in
	if in.ImageTemplateSelector != nil {
		in, out := &in.ImageTemplateSelector, &out.ImageTemplateSelector
		*out = new(ImageTemplateSelector)
		**out = **in
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecurityGroupSelectorTerms != nil {
		in, out := &in.SecurityGroupSelectorTerms, &out.SecurityGroupSelectorTerms
		*out = make([]SelectorTerms, len(*in))
		copy(*out, *in)
	}
	if in.AntiAffinityGroups != nil {
		in, out := &in.AntiAffinityGroups, &out.AntiAffinityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AntiAffinityGroupSelectorTerms != nil {
		in, out := &in.AntiAffinityGroupSelectorTerms, &out.AntiAffinityGroupSelectorTerms
		*out = make([]SelectorTerms, len(*in))
		copy(*out, *in)
	}
	if in.PrivateNetworks != nil {
		in, out := &in.PrivateNetworks, &out.PrivateNetworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrivateNetworkSelectorTerms != nil {
		in, out := &in.PrivateNetworkSelectorTerms, &out.PrivateNetworkSelectorTerms
		*out = make([]SelectorTerms, len(*in))
		copy(*out, *in)
	}
	if in.ElasticIPSelectorTerms != nil {
		in, out := &in.ElasticIPSelectorTerms, &out.ElasticIPSelectorTerms
		*out = make([]SelectorTerms, len(*in))
		copy(*out, *in)
	}
	in.Kubelet.DeepCopyInto(&out.Kubelet)
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.ContainerRegistry != nil {
		in, out := &in.ContainerRegistry, &out.ContainerRegistry
		*out = new(ContainerRegistrySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleNodeClassSpec.
func (in *ExoscaleNodeClassSpec) DeepCopy() *ExoscaleNodeClassSpec {
	if in == nil {
		return nil
	}
	out := new(ExoscaleNodeClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExoscaleNodeClassStatus) DeepCopyInto(out *ExoscaleNodeClassStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]status.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SecurityGroups != nil {
		in, out := &in.SecurityGroups, &out.SecurityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AntiAffinityGroups != nil {
		in, out := &in.AntiAffinityGroups, &out.AntiAffinityGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PrivateNetworks != nil {
		in, out := &in.PrivateNetworks, &out.PrivateNetworks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ElasticIPs != nil {
		in, out := &in.ElasticIPs, &out.ElasticIPs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExoscaleNodeClassStatus.
func (in *ExoscaleNodeClassStatus) DeepCopy() *ExoscaleNodeClassStatus {
	if in == nil {
		return nil
	}
	out := new(ExoscaleNodeClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ImageTemplateSelector) DeepCopyInto(out *ImageTemplateSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ImageTemplateSelector.
func (in *ImageTemplateSelector) DeepCopy() *ImageTemplateSelector {
	if in == nil {
		return nil
	}
	out := new(ImageTemplateSelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeResourceReservation) DeepCopyInto(out *KubeResourceReservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeResourceReservation.
func (in *KubeResourceReservation) DeepCopy() *KubeResourceReservation {
	if in == nil {
		return nil
	}
	out := new(KubeResourceReservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KubeletConfiguration) DeepCopyInto(out *KubeletConfiguration) {
	*out = *in
	if in.ClusterDNS != nil {
		in, out := &in.ClusterDNS, &out.ClusterDNS
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ImageGCHighThresholdPercent != nil {
		in, out := &in.ImageGCHighThresholdPercent, &out.ImageGCHighThresholdPercent
		*out = new(int32)
		**out = **in
	}
	if in.ImageGCLowThresholdPercent != nil {
		in, out := &in.ImageGCLowThresholdPercent, &out.ImageGCLowThresholdPercent
		*out = new(int32)
		**out = **in
	}
	out.KubeReserved = in.KubeReserved
	out.SystemReserved = in.SystemReserved
	if in.FeatureGates != nil {
		in, out := &in.FeatureGates, &out.FeatureGates
		*out = make(map[string]bool, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KubeletConfiguration.
func (in *KubeletConfiguration) DeepCopy() *KubeletConfiguration {
	if in == nil {
		return nil
	}
	out := new(KubeletConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectorTerms) DeepCopyInto(out *SelectorTerms) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectorTerms.
func (in *SelectorTerms) DeepCopy() *SelectorTerms {
	if in == nil {
		return nil
	}
	out := new(SelectorTerms)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SystemResourceReservation) DeepCopyInto(out *SystemResourceReservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SystemResourceReservation.
func (in *SystemResourceReservation) DeepCopy() *SystemResourceReservation {
	if in == nil {
		return nil
	}
	out := new(SystemResourceReservation)
	in.DeepCopyInto(out)
	return out
}
