package cloudprovider

import (
	"context"
	"fmt"

	"github.com/awslabs/operatorpkg/status"
	egov3 "github.com/exoscale/egoscale/v3"
	apiv1 "github.com/exoscale/karpenter-exoscale/apis/v1"
	"github.com/google/uuid"
	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/client-go/dynamic"
	"sigs.k8s.io/controller-runtime/pkg/client"
	karpenterv1 "sigs.k8s.io/karpenter/pkg/apis/v1"
	"sigs.k8s.io/karpenter/pkg/cloudprovider"
)

type CloudProvider struct {
	kubeClient    client.Client
	dynClient     *dynamic.DynamicClient
	exoClient     *egov3.Client
	instanceTypes []*cloudprovider.InstanceType
	clusterID     egov3.UUID
}

func NewCloudProvider(ctx context.Context, kubeClient client.Client, dynClient *dynamic.DynamicClient, exoClient *egov3.Client, zone string) *CloudProvider {
	return &CloudProvider{
		kubeClient: kubeClient,
		dynClient:  dynClient,
		exoClient:  exoClient,
		clusterID:  egov3.UUID(uuid.New().String()), // TODO how i know the cluster ID ? Seems we need to publish it in a configuration variable, it's not magic
		instanceTypes: ConstructInstanceTypes(exoClient, zone, cloudprovider.InstanceTypeOverhead{
			// TODO discover this from somewhere
			KubeReserved: v1.ResourceList{
				v1.ResourceCPU:    resource.MustParse("100m"),
				v1.ResourceMemory: resource.MustParse("100Mi"),
			},
			SystemReserved: v1.ResourceList{
				v1.ResourceCPU:    resource.MustParse("100m"),
				v1.ResourceMemory: resource.MustParse("100Mi"),
			},
		}),
	}
}

func (c *CloudProvider) Create(ctx context.Context, nodeClaim *karpenterv1.NodeClaim) (*karpenterv1.NodeClaim, error) {
	op, err := c.exoClient.CreateSKSNodepool(ctx, c.clusterID, egov3.CreateSKSNodepoolRequest{
		Name:           nodeClaim.Name,
		Description:    fmt.Sprintf("%s [generated by Karpenter]", nodeClaim.Name),
		DiskSize:       50,
		SecurityGroups: []egov3.SecurityGroup{}, // TODO, resolve them from the nodeClaim or the nodeClass, TBD
		InstanceType: &egov3.InstanceType{
			ID: "5e5fb3c6-e076-429d-9b6c-b71f7b27760b", // TODO: resolve this from the nodeClaim or the nodeClass, TBD
		},
		Size:               1,                           // As we create only nodepools through API it's always 1
		AntiAffinityGroups: []egov3.AntiAffinityGroup{}, // TODO, resolve them from the nodeClaim or the nodeClass, TBD
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create node %s: %w", nodeClaim.Name, err)
	}

	op, err = c.exoClient.Wait(ctx, op, egov3.OperationStateSuccess)
	if err != nil {
		return nil, fmt.Errorf("failed to perform node %s creation: %w", nodeClaim.Name, err)
	}

	// Retrieve the nodepool ID
	nodePoolID := op.Reference.ID

	nodePool, err := c.exoClient.GetSKSNodepool(ctx, c.clusterID, nodePoolID)
	if err != nil {
		return nil, fmt.Errorf("failed to get nodepool %s: %w", nodePoolID, err)
	}

	exoInstance, err := c.getInstanceFromExoscaleNodePool(ctx, nodePool)
	if err != nil {
		return nil, fmt.Errorf("failed to get instance for nodepool %s: %w", nodePoolID, err)
	}

	created := &karpenterv1.NodeClaim{
		ObjectMeta: nodeClaim.ObjectMeta,
		Spec:       *nodeClaim.Spec.DeepCopy(),
		Status: karpenterv1.NodeClaimStatus{
			ProviderID: string(nodePoolID),
			NodeName:   exoInstance.Name,
			ImageID:    exoInstance.Template.ID.String(),
		},
	}

	// Is this required in exoscale context ?
	// node := &v1.Node{
	// if err := c.kubeClient.Create(ctx, node); err != nil {
	// 	return created, fmt.Errorf("failed to create node %s: %w", node.Name, err)
	// }

	return created, nil
}

func (c *CloudProvider) Delete(ctx context.Context, nodeClaim *karpenterv1.NodeClaim) error {
	nodePoolID := egov3.UUID(nodeClaim.Status.ProviderID)
	op, err := c.exoClient.DeleteSKSNodepool(ctx, c.clusterID, nodePoolID)
	if err != nil {
		return fmt.Errorf("failed to delete nodepool %s: %w", nodeClaim.Name, err)
	}

	op, err = c.exoClient.Wait(ctx, op, egov3.OperationStateSuccess)
	if err != nil {
		return fmt.Errorf("failed to delete node operation %s for node %s: %w", op.ID, nodeClaim.Name, err)
	}

	return nil
}

func (c *CloudProvider) Get(ctx context.Context, providerID string) (*karpenterv1.NodeClaim, error) {
	nodePool, err := c.exoClient.GetSKSNodepool(ctx, c.clusterID, egov3.UUID(providerID))
	if err != nil {
		return nil, fmt.Errorf("failed to get nodepool %s: %w", providerID, err)
	}

	exoInstance, err := c.getInstanceFromExoscaleNodePool(ctx, nodePool)
	if err != nil {
		return nil, fmt.Errorf("failed to get instance for nodepool %s: %w", providerID, err)
	}

	return nodeClaimFromInstance(nodePool, exoInstance), nil
}

func (c *CloudProvider) List(ctx context.Context) ([]*karpenterv1.NodeClaim, error) {
	cluster, err := c.exoClient.GetSKSCluster(ctx, c.clusterID)
	if err != nil {
		return nil, fmt.Errorf("failed to get cluster %s: %w", c.clusterID, err)
	}

	claims := []*karpenterv1.NodeClaim{}
	for _, pool := range cluster.Nodepools {
		if len(pool.InstancePool.Instances) == 0 {
			// It's not normal, but let's skip it
			// TODO log this
			continue
		}
		claims = append(claims, nodeClaimFromInstance(&pool, &pool.InstancePool.Instances[0]))
	}
	return claims, nil
}

func (c *CloudProvider) GetInstanceTypes(ctx context.Context, nodePool *karpenterv1.NodePool) ([]*cloudprovider.InstanceType, error) {
	return c.instanceTypes, nil
}

func (c *CloudProvider) IsDrifted(_ context.Context, nodeClaim *karpenterv1.NodeClaim) (cloudprovider.DriftReason, error) {
	// TODO: Implement drift method
	//return cloudprovider.DriftReason("DriftReasonNetworkID"), nil
	return "", nil
}

func (c *CloudProvider) GetSupportedNodeClasses() []status.Object {
	return []status.Object{&apiv1.ExoscaleNodeClass{}}
}

func (c *CloudProvider) RepairPolicies() []cloudprovider.RepairPolicy {
	return []cloudprovider.RepairPolicy{}
}

func (c *CloudProvider) Name() string {
	return "Exoscale"
}
