apiVersion: v1
kind: Service
metadata:
  name: karpenter-exoscale-metrics
  labels:
    app: karpenter-exoscale
spec:
  selector:
    app: karpenter-exoscale
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  type: ClusterIP
  clusterIP: None
