kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - https://raw.githubusercontent.com/kubernetes-sigs/karpenter/refs/tags/v1.0.4/pkg/apis/crds/karpenter.sh_nodeclaims.yaml
  - https://raw.githubusercontent.com/kubernetes-sigs/karpenter/refs/tags/v1.0.4/pkg/apis/crds/karpenter.sh_nodepools.yaml
  - karpenter.exoscale.com_exoscalenodeclasses.yaml
