apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: karpenter-exoscale
spec:
  selector:
    matchLabels:
      app: karpenter-exoscale
  endpoints:
    - port: http
      interval: 30s
