name: Publish

on:
- push
- workflow_dispatch

jobs:
  build-images:
    name: build image
    # Note: prefer a tag instead of main
    uses: exoscale/github-actions/.github/workflows/image-build-push-exoscale.yaml@master
    secrets: inherit
    with:
      image-name: karpenter-exoscale
      dockerfile: Dockerfile
      vulnerability-scanner: false
      cache-from: type=gha
      cache-to: type=gha,mode=max
      push-ghcr: false
